version: "3.8"
services:
  landing_page:
    container_name: landing_page
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - "56123:3000"
    networks:
      adysaskinnet:
        ipv4_address: 192.168.0.5

networks:
  adysaskinnet: 
    external: true